# Etapa 1: build da aplicação Angular
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build --configuration=production

# Etapa 2: nginx para servir os arquivos
FROM nginx:alpine

COPY --from=build /app/dist/creditos-front/browser /usr/share/nginx/html

# Remove a configuração default do nginx e adiciona a nossa
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
